### ISSUE TITLE
Is this a use of your project

### ISSUE THREAD

**Issue by leebrian** [CDCgov/CDC-Maps#1]
Is this page, https://www.cdc.gov/endhiv/priorities.html, using your widget? 
![image](https://user-images.githubusercontent.com/307968/70331257-1ee22500-180d-11ea-8787-6fd430fc5a9a.png)

Do you have a list of "in the wild" uses that you could add to the readme?

**Comment by danielimmke** [comment]
Yes it is. The maps are used all over CDC.gov by many centers. There's hundreds in production, so there would be too many to put on there. I already have links to the demos for people who want to see the project in action.

**Comment by leebrian** [comment]
Cool, that's neat that it's so widely used. I find real examples nice to use as references in addition to the fake examples, but that makes sense if it's too hard since there are too many to easily add to a gallery.
